# Generated by Django 3.0.5 on 2020-04-16 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product')),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopone.Product')),
            ],
        ),
    ]
