# Generated by Django 3.0.5 on 2020-04-16 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopone', '0002_productimageitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimageitem',
            old_name='barcode',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='productimageitem',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
