# Generated by Django 3.0.5 on 2020-04-16 14:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopone', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='settypegroup',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopone.Setgroup'),
            preserve_default=False,
        ),
    ]
