# Generated by Django 3.0.5 on 2020-04-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopone', '0005_settypegroup_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setgroup',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='setgroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='setstatus',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='setsubgroup',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='setsubgroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='settypegroup',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='settypegroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='setunit',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
