# Generated by Django 3.0.5 on 2020-04-17 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopone', '0008_ordermember_ordermemberitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermemberitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopone.OrderMember'),
        ),
    ]
