# Generated by Django 3.0.5 on 2020-04-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopone', '0010_auto_20200420_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setgroup',
            name='code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setgroup',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setgroup',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
