# Generated by Django 3.0.5 on 2020-04-20 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopone', '0012_auto_20200420_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopone.Setgroup'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopone.Setstatus'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopone.Setsubgroup'),
        ),
        migrations.AlterField(
            model_name='product',
            name='typegroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopone.Settypegroup'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopone.Setunit'),
        ),
        migrations.AlterField(
            model_name='productimageitem',
            name='slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopone.Product'),
        ),
        migrations.AlterField(
            model_name='setgroup',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='setgroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='setgroup',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='setsubgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopone.Setgroup'),
        ),
        migrations.AlterField(
            model_name='settypegroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopone.Setgroup'),
        ),
        migrations.AlterField(
            model_name='settypegroup',
            name='subgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopone.Setsubgroup'),
        ),
    ]
