# Generated by Django 3.0.5 on 2020-04-23 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopone', '0016_auto_20200422_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagesetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagename', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='page_setting')),
                ('message', models.TextField(blank=True)),
                ('flag', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='shopone.Product')),
            ],
        ),
    ]
