# Generated by Django 3.0.5 on 2020-04-23 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopone', '0017_pagesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesetting',
            name='slug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shopone.Product'),
        ),
    ]
