# Generated by Django 3.0.5 on 2020-04-29 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopone', '0021_orderalluser_orderalluseritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderalluseritem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopone.OrderAllUser'),
        ),
    ]
