# Generated by Django 3.0.5 on 2020-04-29 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopone', '0022_auto_20200429_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderalluser',
            name='dtcreated',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
