# Generated by Django 3.0.5 on 2020-04-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopone', '0023_orderalluser_dtcreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderalluser',
            name='dtcreated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
