# Generated by Django 3.0.5 on 2020-04-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopone', '0024_auto_20200429_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.IntegerField()),
                ('header', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('typedetail', models.CharField(max_length=100)),
                ('flag', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
