# Generated by Django 3.0.5 on 2020-05-05 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopone', '0025_setconditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='setProducttoPromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proname', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('free', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fdate', models.DateField(auto_now_add=True)),
                ('ldate', models.DateField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopone.Product')),
            ],
        ),
    ]
