# Generated by Django 3.0.5 on 2020-05-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopone', '0026_setproducttopromotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setproducttopromotion',
            name='fdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='setproducttopromotion',
            name='ldate',
            field=models.DateField(),
        ),
    ]
