# Generated by Django 3.0.5 on 2020-05-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopone', '0028_setproducttopromotion_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stat_promotion',
            field=models.CharField(default='', max_length=255),
        ),
    ]
