# Generated by Django 3.0.3 on 2020-05-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopone', '0029_product_stat_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='statusBuy',
            field=models.CharField(default='ขาย', max_length=100),
        ),
    ]
