# Generated by Django 3.0.5 on 2020-05-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopone', '0030_cartitem_statusbuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_mem',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
