# Generated by Django 3.0.5 on 2020-05-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopone', '0031_cartitem_price_mem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flag_promotion',
            field=models.CharField(default='normal', max_length=255),
        ),
    ]
