# Generated by Django 3.0.3 on 2020-05-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopone', '0032_product_flag_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderalluseritem',
            name='statusBuy',
            field=models.CharField(default='ขาย', max_length=100),
        ),
    ]
