# Generated by Django 3.0.3 on 2020-05-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopone', '0033_orderalluseritem_statusbuy'),
    ]

    operations = [
        migrations.CreateModel(
            name='setContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=100)),
                ('Phone1', models.CharField(max_length=100)),
                ('Phone2', models.CharField(max_length=100)),
                ('line_id', models.CharField(max_length=100)),
                ('line_link', models.CharField(max_length=100)),
                ('line_qrcode', models.ImageField(blank=True, upload_to='contact')),
                ('email', models.CharField(max_length=100)),
                ('facebook_link', models.CharField(max_length=255)),
                ('pic_contact1', models.ImageField(blank=True, upload_to='contact')),
                ('pic_contact2', models.ImageField(blank=True, upload_to='contact')),
                ('time_openshop', models.DateField()),
                ('time_closeshop', models.DateField()),
                ('time_openoffice', models.DateField()),
                ('time_closeoffice', models.DateField()),
            ],
        ),
    ]
