# Generated by Django 3.0.5 on 2020-05-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopone', '0034_setcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setcontact',
            name='time_closeoffice',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='setcontact',
            name='time_closeshop',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='setcontact',
            name='time_openoffice',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='setcontact',
            name='time_openshop',
            field=models.TimeField(),
        ),
    ]
