# Generated by Django 3.0.5 on 2020-05-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopone', '0037_auto_20200513_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderalluser',
            name='dtCancel',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderalluser',
            name='flagCancel',
            field=models.BooleanField(default=True),
        ),
    ]
